version: '3.8'
services: # 필수
  backend:  # 컨테이너 이름
    image: openjdk:11.0.16-jre # 도커 허브에서 가져올 이미지 이름
    ports: # 본체 컴퓨터랑 컨테이너 포트 연결
      - "8080:8080"
    volumes: # 본체 컴퓨터의 특정 폴더 또는 파일을 컨테이너의 특정 폴더 또는 파일로 연결
      - ./build/libs/jwt_login-0.0.1-SNAPSHOT.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]
    depends_on: # services 목록에서 실행해야할 컨테이너 우선순위 지정
      - my_mysql
  my_mysql:
    image: mysql:latest
    environment: # 환경변수
      MYSQL_ROOT_PASSWORD: qwer1234
    ports:
      - "3309:3309"
    volumes:
      - C:\Users\BIT\Desktop\mysql_data:/var/lib/mysql
