spring:
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/session_login?&serverTimezone=Asia/Seoul
    username: gangnam
    password: qwe123!@#

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true






logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace